// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBASc96xPOff9-I1f28oYw5TsC3-jwn0jA',
    appId: '1:1015298444315:android:2defe55259cff3f3927cbe',
    messagingSenderId: '1015298444315',
    projectId: 'karimpay-6dbf5',
    storageBucket: 'karimpay-6dbf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEi_gW0Dtffac8VLyB-ERr0twWpPlKCMc',
    appId: '1:1015298444315:ios:d6962db05f086f26927cbe',
    messagingSenderId: '1015298444315',
    projectId: 'karimpay-6dbf5',
    storageBucket: 'karimpay-6dbf5.firebasestorage.app',
    iosBundleId: 'com.example.karimPay',
  );

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAhpGn-amwGAZt56eJUwr6ZTMoCNuNNNB0",
      authDomain: "karimpay-6dbf5.firebaseapp.com",
      projectId: "karimpay-6dbf5",
      storageBucket: "karimpay-6dbf5.firebasestorage.app",
      messagingSenderId: "1015298444315",
      appId: "1:1015298444315:web:1f771076d58ed852927cbe",
      measurementId: "G-RGW9DH017W");
}
